# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConvertTo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import  QDoubleValidator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 234)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 80, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.convertTo = QtWidgets.QPushButton(self.centralwidget)
        self.convertTo.setGeometry(QtCore.QRect(200, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.convertTo.setFont(font)
        self.convertTo.setObjectName("convertTo")
        self.label_Date = QtWidgets.QLabel(self.centralwidget)
        self.label_Date.setGeometry(QtCore.QRect(0, 160, 500, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Date.setFont(font)
        self.label_Date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date.setObjectName("label_Date")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.textbox_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox_1.setGeometry(QtCore.QRect(20, 100, 171, 21))

        self.textbox_1.setValidator(QDoubleValidator(0.0,999.0, 4, self.textbox_1))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.textbox_1.setFont(font)
        self.textbox_1.setObjectName("textbox_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.textBox_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textBox_2.setGeometry(QtCore.QRect(260, 100, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBox_2.setFont(font)
        self.textBox_2.setObjectName("textBox_2")
        self.textBox_2.setReadOnly(True)
        self.label_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_rate.setGeometry(QtCore.QRect(130, 190, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rate.setFont(font)
        self.label_rate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rate.setObjectName("label_rate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.rename()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертатор валют"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Россия"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Украина"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Европа"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Китай"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Казахстан"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "США"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Белорусь"))
        self.convertTo.setText(_translate("MainWindow", "⇆"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Россия"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Украина"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Европа"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "Китай"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "Казахстан"))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "США"))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "Белорусь"))
        self.label_1.setText(_translate("MainWindow", "Российский рубль"))
        self.label_2.setText(_translate("MainWindow", "Российский рубль"))

    def changeComb1(self, s):
        _translate = QtCore.QCoreApplication.translate
        match s:
            case 0:
                self.label_1.setText(_translate("MainWindow", "Российский рубль"))
            case 5:
                self.label_1.setText(_translate("MainWindow", "Доллар США"))
            case 2:
                self.label_1.setText(_translate("MainWindow", "Евро"))
            case 4:
                self.label_1.setText(_translate("MainWindow", "Казахстанских тенге"))
            case 3:
                self.label_1.setText(_translate("MainWindow", "Китайский юань"))
            case 6:
                self.label_1.setText(_translate("MainWindow", "Белорусский рубль"))
            case 1:
                self.label_1.setText(_translate("MainWindow", "Украинских гривен"))
    def changeComb2(self, s):
        _translate = QtCore.QCoreApplication.translate
        match s:
            case 0:
                self.label_2.setText(_translate("MainWindow", "Российский рубль"))
            case 5:
                self.label_2.setText(_translate("MainWindow", "Доллар США"))
            case 2:
                self.label_2.setText(_translate("MainWindow", "Евро"))
            case 4:
                self.label_2.setText(_translate("MainWindow", "Казахстанских тенге"))
            case 3:
                self.label_2.setText(_translate("MainWindow", "Китайский юань"))
            case 6:
                self.label_2.setText(_translate("MainWindow", "Белорусский рубль"))
            case 1:
                self.label_2.setText(_translate("MainWindow", "Украинских гривен"))

    def covertCurrency(self):
        from datetime import datetime, date
        import requests
        from bs4 import BeautifulSoup as BS

        r = requests.get("https://cbr.ru/curreNcy_base/daily/")
        html = BS(r.content, 'html.parser')

        table1 = html.find('table')
        headers = []
        result = float(self.textbox_1.text().replace(',', '.'))
        rate = 1
        currency = 1
        for i in table1.find_all('tr'):
            title = i.text.split("\n")[1:-1]
            headers.append(title)
        for i in headers:
            if (i[3] == self.label_1.text()):
                result = (float(i[4].replace(',', '.'))/float(i[2].replace(',', '.')) * float(self.textbox_1.text().replace(',', '.')))
                rate = (float(i[4].replace(',', '.'))/float(i[2].replace(',', '.')))
            if (i[3] == self.label_2.text()):
                currency = (float(i[4].replace(',', '.'))/float(i[2].replace(',', '.')))
        self.label_Date.setText("Текущая дата и время: " + str(datetime.today())[: str(datetime.today()).rfind('.')])
        self.label_rate.setText("Текущий курс составляет: " + str(round(currency/rate, 4)).replace('.', ','))
        self.textBox_2.setText(str(round(result/currency , 4)).replace('.', ','))

    def rename(self):
        self.comboBox_1.activated.connect(self.changeComb1)
        self.comboBox_2.activated.connect(self.changeComb2)
        self.convertTo.clicked.connect(self.covertCurrency)





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

